
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
   
   
urlvalidate: http://localhost:3003

corsOrigins: http://localhost:8081,http://localhost:8989,http://localhost:3000,http://localhost:8080,http://192.168.0.2:3000,http://192.168.0.3:3000, http://192.168.0.4:3000, http://192.168.0.5:3000, http://192.168.0.6:3000, http://192.168.0.7:3000, http://192.168.0.8:3000
