spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: schemaService
          uri: lb://schemaService
          predicates:
            - Path=/api/**
          filters:
            - name: CircuitBreaker
              args:
                name: schemaService             
        - id: party
          uri: lb://party
          predicates:
            - Path=/party/**
          filters:
            - name: CircuitBreaker
              args:
                name: party
                fallbackuri: forward:/Fallback   
        - id: producto
          uri: lb://product
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: product
                fallbackuri: forward:/Fallback   
        - id: common
          uri: lb://common
          predicates:
            - Path=/common/**
          filters:
            - name: CircuitBreaker
              args:
                name: common
                fallbackuri: forward:/Fallback
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: order
                fallbackuri: forward:/Fallback
      globalcors:
        corsConfigurations:
          "[/**]":
            allowed-origins: "http://localhost:3001"
            allowed-methods:
              - "*"
            allowed-headers:
              - "*"
            allow-credentials: true
